# Generated by Django 2.1.4 on 2019-10-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('content', models.FileField(upload_to='')),
            ],
        ),
    ]
