# Generated by Django 2.1.4 on 2019-10-17 21:11

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='timestamp',
            field=models.FloatField(default=time.time),
        ),
    ]
